# Site settings
title: 'Cerebrux Code'
email: mail@cerebrux.net
description: > # this means to ignore newlines until "baseurl:"
 Αποθετήριο κώδικα Cerebrux
baseurl:  /blog/
url:  http://code.cerebrux.net
twitter_username: cerebrux
github_username: cerebrux
google_site_verification: 0X-0Z0IU7ddvscGoWRR5S-BQjZJqXIjSw_CiqFLKGoQ
# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


