# Resources settings
source:      .
layouts:     ./_layouts
timezone:    Europe/Athens

# Site settings
title: 'Cerebrux Code'
email: mail@cerebrux.net
author: Cerebrux
owner_name: Cerebrux.net
github_username: cerebrux
repo: cerebruxcode.github.io

#Server
url: http://code.cerebrux.net
github: https://github.com/CerebruxCode/
baseurl: ""

#Page settings
future: true
show_drafts: nil
lsi: true
published: false
safe: false
permalink: /:year/:month/:day/:title/
markdown: kramdown
excerpt_separator: '<!-- more -->'

exclude: ['README.md','Manifest.md']
include: ['robots.txt']

# Description
description: "Αποθετήριο κώδικα Cerebrux"
# Keywords
keywords:
        - "cerebrux"
        - "linux"
        - "κώδικας"
        - "αποθετήριο"
        - "ubuntu"
        - "debian"
        - "arch linux"
        - "opensuse"
        - "fedora"
        - "ανοιχτό"
        - "ελεύθερο"
        - "λογισμικό"
        
#Update configuration
versioncode: 1
        #The current versioncode.
versionname: "1.0.1"
        #The current versionname.
remind: true
        #Whether to remind you to upgrade the latest version when there is the latest version.

#Others
#Google
google_site_verification: "0X-0Z0IU7ddvscGoWRR5S-BQjZJqXIjSw_CiqFLKGoQ"

 
