title: 'Cerebrux Code'
email: mail@cerebrux.net
description: 'Μάθε παιδί μου Linux | Αποθετήριο κώδικά Cerebrux.'
url: 'https://code.cerebrux.net'
twitter_username: cerebrux
github_username: cerebrux
future: true
excerpt_separator: '---'
gems:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed
    - jemoji
sass:
    style: compressed
collections:
    docs: {output: true, permalink: '/docs/:path/'}
defaults:
    - {scope: {type: docs}, values: {layout: docs}}
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:year/:month/:day/:title'}}
    - {scope: {path: ""}, values: {image: {path: /images/opengraph.png, width: 1200, height: 630}}}
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
include:
    - _pages
google_site_verification: 0X-0Z0IU7ddvscGoWRR5S-BQjZJqXIjSw_CiqFLKGoQ
twitter:
    username: cerebrux
logo: /images/opengraph.png

# github.com/untra/polyglot
languages:
  - el
default_lang: el
exclude_from_localization:
  - bower_components
  - css
  - images
  - js
  - lib
  - script
parallel_localization: true
